# Generated by Django 5.2 on 2025-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phot', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('facebook_linnk', models.URLField(max_length=255)),
                ('google_linnk', models.URLField(max_length=255)),
                ('twitter_linnk', models.URLField(max_length=255)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
