# Generated by Django 5.2 on 2025-04-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_team_twitter_linnk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='phot',
            new_name='photo',
        ),
    ]
