# Generated by Django 5.2 on 2025-04-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_phot_team_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook_linnk',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='google_linnk',
            new_name='google_link',
        ),
    ]
